disabled_rules:
- trailing_whitespace
- todo

excluded:
- Pods

line_length:
    warning: 170
    error: 600
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

identifier_name:
  allowed_symbols:
        - _
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
