# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all dependencies
inhibit_all_warnings!

target 'Spotlight-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotlight-SwiftUI
  pod 'SwiftGen', '~> 6.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 7.0'
end
